export const countries = new Map([
    ["FRA", "france"],
    ["REU", "france"],
    ["BRA", "brazil"],
    ["ENG", "england"],
    ["POR", "portugal"],
    ["EGY", "egypt"],
    ["KOR", "south korea"],
    ["GER", "germany"],
    ["ITA", "italy"],
    ["POL", "poland"],
    ["SWE", "sweden"],
    ["NOR", "norway"],
    ["CRO", "croatia"],
    ["ESP", "spain"],
    ["URU", "uruguay"],
    ["SEN", "senegal"],
    ["JAM", "jamaica"],
    ["GAB", "gabon"],
    ["ARG", "argentina"],
    ["COL", "colombia"],
    ["NED", "netherlands"],
    ["CZE", "czech republic"],
    ["HUN", "hungary"],
    ["NGA", "nigeria"],
    ["BIH", "bosnia"],
    ["SRB", "serbia"],
    ["HON", "honduras"],
    ["SVK", "slovakia"],
    ["CAN", "canada"],
    ["TUN", "tunisia"],
    ["GUI", "guinea"],
    ["GHA", "ghana"],
    ["GHA", "ghana"],
    ["USA", "united states"],
    ["BEL", "belgium"],
    ["DEN", "denmark"],
    ["MAR", "morocco"],
]);
